feat: deployment scripts

diff --git a/scripts/create-service-account b/scripts/create-service-account
--- a/scripts/create-service-account
+++ b/scripts/create-service-account
@@ -1,34 +1,69 @@
 #!/usr/bin/env bash
 
-PROJECT_ID=$1
+DESCRIPTION=""
+roles=()
+
+while [[ -n "$1" ]]; do
+  case $1 in
+  --name)
+    NAME="$2"
+    shift
+    ;;
+  --project)
+    PROJECT_ID="$2"
+    shift
+    ;;
+  --key)
+    KEY="true"
+    ;;
+  --description)
+    DESCRIPTION="$2"
+    shift
+    ;;
+  --pubsub)
+    roles=("${roles[@]}" "roles/pubsub.publisher")
+    ;;
+  --compute)
+    roles=("${roles[@]}" "roles/compute.viewer" "roles/storage.objectViewer" "roles/logging.logWriter" "roles/monitoring.metricWriter")
+    ;;
+  --datastore)
+    roles=("${roles[@]}" "roles/datastore.user")
+    ;;
+  --bigquery)
+    roles=("${roles[@]}" "roles/bigquery.dataViewer" "roles/bigquery.user")
+    ;;
+  --redis)
+    roles=("${roles[@]}" "roles/redis.editor")
+    ;;
+  *)
+    echo "unknown parameter"
+    exit 1
+    ;;
+  esac
+  shift
+done
+
+[[ -z "$NAME" ]] && echo "error: require name" && exit 1
+[[ -z "$roles" ]] && echo "error: invalid role" && exit 1
 [[ -z "$PROJECT_ID" ]] && echo "error: require project ID" && exit 1
 
-if ! gcloud projects list | awk '{ print $1 }' | grep -Eq "^${PROJECT_ID}$" ; then
+# check project id exists
+if ! gcloud projects list | awk '{ print $1 }' | grep -Eq "^${PROJECT_ID}$"; then
   echo "error: invalid project ID" && exit 1
 fi
 
-SERVICE_ACCOUNT_ID="pubsub-publish-sa"
-DESCRIPTION="Used within AWS Lambda to publish to PubSub"
-DISPLAY_NAME="PubSub publisher"
+gcloud iam service-accounts create "$NAME" \
+  --description="$DESCRIPTION" \
+  --display-name="$NAME"
 
-while [[ -n "$1" ]] ; do
-  case $1 in
-  --pubsub)
-    ROLE="roles/pubsub.publisher"
-    ;;
-  esac
-shift
+for role in "${roles[@]}"; do
+  echo "adding role: $role"
+  gcloud projects add-iam-policy-binding "$PROJECT_ID" \
+    --member="serviceAccount:${NAME}@${PROJECT_ID}.iam.gserviceaccount.com" \
+    --role="$role"
 done
 
-[[ -z "$ROLE" ]] && echo "error: invalid role" && exit 1
-
-gcloud iam service-accounts create "$SERVICE_ACCOUNT_ID" \
-    --description="$DESCRIPTION" \
-    --display-name="$DISPLAY_NAME"
-
-gcloud projects add-iam-policy-binding "$PROJECT_ID" \
-    --member="serviceAccount:${SERVICE_ACCOUNT_ID}@${PROJECT_ID}.iam.gserviceaccount.com" \
-    --role="$ROLE"
-
-gcloud iam service-accounts keys create $(dirname $0)/../key.json \
---iam-account "${SERVICE_ACCOUNT_ID}@${PROJECT_ID}.iam.gserviceaccount.com"
+if [[ "$KEY" == "true" ]]; then
+  gcloud iam service-accounts keys create $(dirname $0)/../key.json \
+    --iam-account "${NAME}@${PROJECT_ID}.iam.gserviceaccount.com"
+fi
