refactor: improvements, fixes

diff --git a/scripts/deploy-app-engine-canary b/scripts/deploy-app-engine-canary
--- a/scripts/deploy-app-engine-canary
+++ b/scripts/deploy-app-engine-canary
@@ -30,6 +30,10 @@ while [[ -n "$1" ]]; do
   --canary)
     CANARY=true
     ;;
+  --config)
+    CONFIG="$2"
+    shift
+    ;;
   esac
   shift
 done
@@ -41,16 +45,26 @@ OLD_VERSION=$(gcloud app versions list | awk '{ print $2 }' | sort -k1.5n | head
 
 # check variables have been defined
 if [[ -z "$VERSION" ]] ; then
-  PREFIX=$(echo "$OLD_VERSION" | sed 's/^\(.*-.*-\)\(.*\)$/\1/')
-  LATEST=$(echo "$OLD_VERSION" | sed 's/^\(.*-.*-\)\(.*\)$/\2/')
-
-
+  if [[ -z "$OLD_VERSION" ]] ; then
+    VERSION="v0.0.1"
+  else
+    PREFIX=$(echo "$OLD_VERSION" | sed 's/^\(.*-.*-\)\(.*\)$/\1/')
+    LATEST=$(echo "$OLD_VERSION" | sed 's/^\(.*-.*-\)\(.*\)$/\2/')
+    INCREMENTED=$(expr $(($LATEST + 1)))
+    VERSION=$(echo "${PREFIX}${INCREMENTED}" | sed 's/-/\./g')
+  fi
 fi
+
 [[ -z "$PROJECT" ]] && echo "warning: project using gcloud default"
+[[ -z "$CONFIG" ]] && echo "error: require config" && exit 1
+
+SERVICE=$(cat $CONFIG | grep "service:" | sed 's/service: \(\w*\)/\1'/)
 
 echo "VERSION $VERSION"
 echo "PROJECT $PROJECT"
 echo "CANARY $CANARY"
+echo "CONFIG $CONFIG"
+echo "SERVICE $SERVICE"
 echo "PROMOTE $PROMOTE"
 
 # check the version is in the format v0.0.0
@@ -64,7 +78,7 @@ else
 fi
 
 # default base command
-command="gcloud app deploy --appyaml="$DIR/../app.yaml" --quiet --version $VERSION"
+command="gcloud app deploy --appyaml="$CONFIG" --quiet --version $VERSION"
 
 # conditionally add promote / no-promote
 [[ "$PROMOTE" == "true" ]] && command="$command --promote" || command="$command --no-promote"
@@ -75,5 +89,5 @@ eval "$command"
 # rollout canary
 if [[ "$CANARY" == "true" ]]; then
   echo "running canary deployment"
-  gcloud app services set-traffic default --quiet --splits="$OLD_VERSION"=0.9,"$VERSION"=0.1
+  gcloud app services set-traffic "$SERVICE" --quiet --splits="$OLD_VERSION"=0.9,"$VERSION"=0.1
 fi
